---

kafka_home: /usr/lib/kafka
kafka_conf_dir: /etc/kafka-confluent/conf

kafka_server_conf_dir: "{{ kafka_conf_dir }}/kafka"
kafka_schema_registry_conf_dir: "{{ kafka_conf_dir }}/schema-registry"

kafka_log_dir: /data01/log/kafka

data_dir1: /data01/kafka-data
data_dir2: /data02/kafka-data

data_dir: "{{ data_dir1 }},{{ data_dir2 }}"

zk1_host: "{{ hostvars[groups['zookeeper-hosts'][0]]['inventory_hostname'] }}"
zk2_host: "{{ hostvars[groups['zookeeper-hosts'][1]]['inventory_hostname'] }}"
zk3_host: "{{ hostvars[groups['zookeeper-hosts'][2]]['inventory_hostname'] }}"

zk_hosts: "{{ zk1_host }}:2181,{{ zk2_host }}:2181,{{ zk3_host }}:2181"

broker_node1: "{{ hostvars[groups['kafka-hosts'][0]]['inventory_hostname'] }}"
broker_node2: "{{ hostvars[groups['kafka-hosts'][1]]['inventory_hostname'] }}"

kafka_dist_name: confluent-oss-3.3.1-2.11
kafka_dist_file: "{{ kafka_dist_name }}.tar.gz"
kafka_dist_dir: confluent-3.3.1

kafka_temp_dir: /tmp/kafka

java_home: /usr/lib/jdk

delete_topic_enable: true
offsets_topic_repl_factor: 2
